#!/usr/bin/env python3
"""Bundles the editor's ES modules (web/editor.js and what it imports) into
one script, build/editor.js, served at /s/editor.js?v=<version>: one
request, one immutable cache entry. Each module runs in its own function
scope, in dependency order; `import { a, b as c } from "./x.js"` becomes a
read of x's exports and `export` marks what a module returns. Only the
forms our modules use are accepted; anything else stops the build.
usage: tools/bundle.py"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")
IMPORT = re.compile(r'^import \{([^}]*)\} from "\./([a-z_]+)\.js";$', re.M)
EXPORT_DECL = re.compile(r"^export (async function|function|class|const|let) ([A-Za-z_$][\w$]*)", re.M)

order, seen = [], set()


def load(name, stack=()):
    if name in seen:
        return
    if name in stack:
        sys.exit(f"import cycle: {' -> '.join(stack + (name,))}")
    src = open(os.path.join(WEB, name + ".js"), encoding="utf-8").read()
    for m in IMPORT.finditer(src):
        load(m.group(2), stack + (name,))
    seen.add(name)
    order.append((name, src))


load("editor")
out = ["// GENERATED by tools/bundle.py from web/*.js: do not edit.", "(() => {", '"use strict";']
for name, src in order:
    exports = [m.group(2) for m in EXPORT_DECL.finditer(src)]

    def imp(m):
        names = []
        for part in m.group(1).split(","):
            part = part.strip()
            if not part:
                continue
            a, _, b = part.partition(" as ")
            names.append(f"{a.strip()}: {b.strip()}" if b else a.strip())
        return "const { " + ", ".join(names) + " } = m_" + m.group(2) + ";"

    body = IMPORT.sub(imp, src)
    body = EXPORT_DECL.sub(lambda m: m.group(1) + " " + m.group(2), body)
    if re.search(r"^\s*(import|export)\b", body, re.M):
        sys.exit(f"web/{name}.js: an import or export form the bundler does not know")
    out.append(f"const m_{name} = (() => {{\n{body}\nreturn {{ {', '.join(exports)} }};\n}})();")
out.append("})();")
os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
js = "\n".join(out) + "\n"
path = os.path.join(ROOT, "build", "editor.js")
if not os.path.exists(path) or open(path, encoding="utf-8").read() != js:
    open(path, "w", encoding="utf-8").write(js)
print(f"bundled {len(order)} modules ({', '.join(n for n, _ in order)}): {len(js)} bytes")
