#!/usr/bin/env python3
"""Generates src/md_tables.rs: the data CommonMark needs that Rust's std
does not have. Entities from vendor/whatwg/entities.json (HTML5's named
character references, only those ending in ';', which is all CommonMark
recognizes); Unicode punctuation (categories P and S, CommonMark 0.31)
and whitespace (Zs) from Python's unicodedata."""
import json, sys, unicodedata, hashlib
src = open("vendor/whatwg/entities.json", "rb").read()
assert hashlib.sha256(src).hexdigest() == "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
ents = sorted((k[1:-1], v["characters"]) for k, v in json.loads(src).items() if k.endswith(";"))
def ranges(pred):
    out, start = [], None
    for cp in range(0x110000 + 1):
        ok = cp < 0x110000 and pred(chr(cp))
        if ok and start is None: start = cp
        if not ok and start is not None:
            out.append((start, cp - 1)); start = None
    return out
punct = ranges(lambda c: unicodedata.category(c)[0] in "PS")
space = ranges(lambda c: unicodedata.category(c) == "Zs")
def rs(s):
    return '"' + "".join(c if c.isascii() and c.isprintable() and c not in '"\\' else "\\u{%x}" % ord(c) for c in s) + '"'
with open("src/md_tables.rs", "w") as f:
    f.write("// GENERATED by tools/gen_md_tables.py (Unicode %s). Do not edit.\n\n" % unicodedata.unidata_version)
    f.write("/// HTML5 named character references (name without & and ;), sorted.\n")
    f.write("pub static ENTITIES: [(&str, &str); %d] = [\n" % len(ents))
    for k, v in ents:
        f.write("    (%s, %s),\n" % (rs(k), rs(v)))
    f.write("];\n\n/// Unicode punctuation and symbols (P, S), as ranges.\n")
    f.write("pub static PUNCT: [(u32, u32); %d] = [\n" % len(punct))
    for a, b in punct:
        f.write("    (0x%x, 0x%x),\n" % (a, b))
    f.write("];\n\n/// Unicode space separators (Zs), as ranges.\n")
    f.write("pub static SPACE: [(u32, u32); %d] = [\n" % len(space))
    for a, b in space:
        f.write("    (0x%x, 0x%x),\n" % (a, b))
    f.write("];\n")
print(len(ents), "entities,", len(punct), "punctuation ranges,", len(space), "space ranges")
